version: '3'
services:
  frontend:
    build:
     context: .
     dockerfile: dockerfileApache
    depends_on:
      - middleware
    ports:
      - "80:80"
    volumes:
      - ./TPIWCComponents/:/usr/local/apache2/htdocs/
